### ISSUE TITLE
Compile with node-gyp

### ISSUE THREAD

**Issue by clayrisser** [jamrizzi/gtk-node#5]
https://github.com/nodejs/node-gyp

**Comment by clayrisser** [comment]
I tried to compile with node-gyp, but I get a Dynamic Linking Error undefined symbol when I try and run the application. It compiles just fine but seems to fail at runtime. Anyone have any clues to what is going on?

```sh
/home/jamrizzi/Downloads/node-gtk3/node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: /home/jamrizzi/Downloads/node-gtk3/build/Release/window.so: undefined symbol: gtk_window_new
    at new DynamicLibrary (/home/jamrizzi/Downloads/node-gtk3/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (/home/jamrizzi/Downloads/node-gtk3/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (/home/jamrizzi/Downloads/node-gtk3/lib/window/index.js:26:28)
    at Module._compile (module.js:573:30)
    at loader (/home/jamrizzi/Downloads/node-gtk3/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jamrizzi/Downloads/node-gtk3/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
error Command failed with exit code 1.

```

**Comment by clayrisser** [comment]
You can duplication this error from the _node-gyp_ branch.

https://github.com/jamrizzi/node-gtk3/tree/node-gyp

**Comment by clayrisser** [comment]
I made some headway with node-gyp.

4abb53825180637a9b9d71576585cf63ae59a8e6

It turns out that the problem is with the order of the cflags. The cflags are supposed to be placed after the input/output files are specified, but node-gyp does it in the wrong order.

https://github.com/nodejs/node-gyp/issues/1298

https://stackoverflow.com/questions/46354002/how-do-i-add-flags-after-input-and-output-specified-not-before-with-node-gyp

**Comment by clayrisser** [comment]
I had to create a custom patch for node-gyp in order to get this to work. It works though!

https://github.com/jamrizzi/node-gyp/commit/f47939c6d0961ac99ed9288086a7589223a5da07

https://github.com/jamrizzi/node-gtk3/commit/efbfd8fb614b0ec284bda9cdde4efb87980ea32c
